import { Calendar, TrendingUp, Users, MapPin, Plane, Clock, BarChart3 } from "lucide-react";
import { ReportsConfig } from "@/components/dashboard/ReportsPage";

export const reportsConfigs: Record<string, ReportsConfig> = {
  border: {
    role: 'border',
    title: 'Border Control Reports',
    description: 'Generate and download comprehensive border control reports',
    apiEndpoint: '/border/reports',
    themeColor: 'primary',
    templates: [
      {
        id: 1,
        name: "Daily Operations Report",
        description: "Comprehensive daily border control activities",
        icon: <Calendar size={16} className="text-primary" />,
        frequency: "Daily",
        lastGenerated: "Today, 08:00",
      },
      {
        id: 2,
        name: "Weekly Performance Report",
        description: "Weekly verification statistics and trends",
        icon: <TrendingUp size={16} className="text-success" />,
        frequency: "Weekly",
        lastGenerated: "Monday, 08:00",
      },
      {
        id: 3,
        name: "Officer Activity Report",
        description: "Individual officer performance metrics",
        icon: <Users size={16} className="text-accent" />,
        frequency: "On-demand",
        lastGenerated: "2 days ago",
      },
      {
        id: 4,
        name: "Port Statistics Report",
        description: "Port-by-port verification analytics",
        icon: <MapPin size={16} className="text-primary" />,
        frequency: "Weekly",
        lastGenerated: "Monday, 08:00",
      },
      {
        id: 5,
        name: "Denial Analysis Report",
        description: "Analysis of denied entries and reasons",
        icon: <BarChart3 size={16} className="text-danger" />,
        frequency: "Monthly",
        lastGenerated: "1st of month",
      },
      {
        id: 6,
        name: "Processing Time Report",
        description: "Average processing times and efficiency",
        icon: <Clock size={16} className="text-warning" />,
        frequency: "Weekly",
        lastGenerated: "Monday, 08:00",
      },
    ],
    recentReports: [
      { name: "Daily Operations - March 11, 2026", date: "Today", size: "2.4 MB", format: "PDF" },
      { name: "Weekly Performance - Week 10", date: "Yesterday", size: "5.1 MB", format: "PDF" },
      { name: "Officer Activity - February 2026", date: "2 days ago", size: "3.8 MB", format: "Excel" },
      { name: "Port Statistics - Week 9", date: "1 week ago", size: "4.2 MB", format: "PDF" },
    ],
    quickStats: {
      reports_generated: 156,
      avg_generation_time: "12s",
      total_downloads: 892,
      scheduled_reports: 8,
    },
    insights: [
      { title: "Most Downloaded", value: "Daily Operations Report" },
      { title: "Trending Up", value: "Officer Activity Reports +24%" },
      { title: "Next Scheduled", value: "Weekly Performance - Tomorrow 08:00" },
    ],
  },

  airline: {
    role: 'airline',
    title: 'Airline Verification Reports',
    description: 'Generate and download comprehensive airline verification reports',
    apiEndpoint: '', // No backend yet for airline
    themeColor: 'blue-600',
    templates: [
      {
        id: 1,
        name: "Daily Verification Report",
        description: "Comprehensive daily passenger verification activities",
        icon: <Calendar size={16} className="text-primary" />,
        frequency: "Daily",
        lastGenerated: "Today, 08:00",
      },
      {
        id: 2,
        name: "Weekly Performance Report",
        description: "Weekly verification statistics and trends",
        icon: <TrendingUp size={16} className="text-success" />,
        frequency: "Weekly",
        lastGenerated: "Monday, 08:00",
      },
      {
        id: 3,
        name: "Staff Activity Report",
        description: "Individual staff performance metrics",
        icon: <Users size={16} className="text-accent" />,
        frequency: "On-demand",
        lastGenerated: "2 days ago",
      },
      {
        id: 4,
        name: "Flight Statistics Report",
        description: "Flight-by-flight verification analytics",
        icon: <Plane size={16} className="text-blue-600" />,
        frequency: "Weekly",
        lastGenerated: "Monday, 08:00",
      },
      {
        id: 5,
        name: "Denial Analysis Report",
        description: "Analysis of denied boarding and reasons",
        icon: <BarChart3 size={16} className="text-danger" />,
        frequency: "Monthly",
        lastGenerated: "1st of month",
      },
      {
        id: 6,
        name: "Processing Time Report",
        description: "Average processing times and efficiency",
        icon: <Clock size={16} className="text-warning" />,
        frequency: "Weekly",
        lastGenerated: "Monday, 08:00",
      },
    ],
    recentReports: [
      { name: "Daily Verification - March 11, 2026", date: "Today", size: "1.8 MB", format: "PDF" },
      { name: "Weekly Performance - Week 10", date: "Yesterday", size: "4.2 MB", format: "PDF" },
      { name: "Staff Activity - February 2026", date: "2 days ago", size: "2.9 MB", format: "Excel" },
      { name: "Flight Statistics - Week 9", date: "1 week ago", size: "3.5 MB", format: "PDF" },
    ],
    quickStats: {
      reports_generated: 124,
      avg_generation_time: "9s",
      total_downloads: 687,
      scheduled_reports: 6,
    },
    insights: [
      { title: "Most Downloaded", value: "Daily Verification Report" },
      { title: "Trending Up", value: "Staff Activity Reports +18%" },
      { title: "Next Scheduled", value: "Weekly Performance - Tomorrow 08:00" },
    ],
  },
};
